import Foundation

public struct ExclusionPolicy: Sendable {
    public var blockedBundleIDs: Set<String>
    public static let concealedType = "org.nspasteboard.ConcealedType"
    public static let transientType = "org.nspasteboard.TransientType"
    public static let autoGeneratedType = "org.nspasteboard.AutoGeneratedType"

    public static let defaultBlocked: Set<String> = [
        "com.agilebits.onepassword7", "com.agilebits.onepassword",
        "com.1password.1password", "com.lastpass.LastPass",
        "in.sinew.Walletx", "com.bitwarden.desktop", "com.dashlane.dashlanephonefinal",
    ]

    public init(blockedBundleIDs: Set<String> = ExclusionPolicy.defaultBlocked) {
        self.blockedBundleIDs = blockedBundleIDs
    }

    public func shouldCapture(_ s: PasteboardSnapshot) -> Bool {
        if s.markerTypes.contains(Self.concealedType) { return false }
        if s.markerTypes.contains(Self.transientType) { return false }
        if s.markerTypes.contains(Self.autoGeneratedType) { return false }
        if let id = s.sourceAppBundleID, blockedBundleIDs.contains(id) { return false }
        return true
    }
}
